#pragma once

#define WINDOW_TITLE  "Centipede"
#define CELL_SIZE 8
#define GRID_COLS 30
#define GRID_ROWS 32

#define WINDOW_SCALE 4
#define WINDOW_WIDTH (GRID_COLS * CELL_SIZE * WINDOW_SCALE)
#define WINDOW_HEIGHT (GRID_ROWS * CELL_SIZE * WINDOW_SCALE)

#define CELL_PX (CELL_SIZE * WINDOW_SCALE) // pixel size of one cell

#define PLAYER_ZONE_TOP (WINDOW_HEIGHT * 0.70f)

#define SPRITE_W 7
#define SPRITE_H 8
#define PLAYER_W (SPRITE_W * WINDOW_SCALE)
#define PLAYER_H (SPRITE_H * WINDOW_SCALE)
#define PLAYER_SPEED (100.0f * float(WINDOW_SCALE))

#define BULLET_W (1 * WINDOW_SCALE)
#define BULLET_H (6 * WINDOW_SCALE)
#define BULLET_SPEED (400.0f * float(WINDOW_SCALE))

#define MUSHROOM_SPRITE_W 8
#define MUSHROOM_SPRITE_H 8
#define MUSHROOM_W (MUSHROOM_SPRITE_W * WINDOW_SCALE)
#define MUSHROOM_H (MUSHROOM_SPRITE_H * WINDOW_SCALE)
#define MUSHROOM_MAX_HP 4

#define CENTIPEDE_SPEED (100.0f * float(WINDOW_SCALE))
#define CENTIPEDE_SPEED_MIN (180.0f * float(WINDOW_SCALE))
#define CENTIPEDE_SPEED_INC (10.0f * float(WINDOW_SCALE))
#define CENTIPEDE_LENGTH 12
#define CENTIPEDE_HEAD_SPEED_BONUS (40.0f * float(WINDOW_SCALE))

#define SPIDER_FRAME_W 16
#define SPIDER_FRAME_H 8
#define SPIDER_W (SPIDER_FRAME_W * WINDOW_SCALE)
#define SPIDER_H (SPIDER_FRAME_H * WINDOW_SCALE)
#define SPIDER_SPEED (80.0f * float(WINDOW_SCALE))
#define SPIDER_FRAME_RATE 0.08f
#define SPIDER_SPAWN_RATE 15.0f
#define SPIDER_FRAMES 8
#define SPIDER_CLOSE_DIST (3 * CELL_PX)
#define SPIDER_MID_DIST (6 * CELL_PX)

#define FLEA_FRAME_W 16
#define FLEA_FRAME_H 8
#define FLEA_W (FLEA_FRAME_W * WINDOW_SCALE)
#define FLEA_H (FLEA_FRAME_H * WINDOW_SCALE)
#define FLEA_SPEED (185.0f * float(WINDOW_SCALE))
#define FLEA_SPEED_FAST (250.0f * float(WINDOW_SCALE))
#define FLEA_FRAME_RATE 0.08f
#define FLEA_FRAMES 4
#define FLEA_MUSHROOM_MIN 5
#define FLEA_MUSHROOM_MAX 8
#define FLEA_SPAWN_THRESHOLD 5

#define SCORPION_FRAME_W 16
#define SCORPION_FRAME_H 8
#define SCORPION_W (SCORPION_FRAME_W * WINDOW_SCALE)
#define SCORPION_H (SCORPION_FRAME_H * WINDOW_SCALE)
#define SCORPION_SPEED (70.0f * float(WINDOW_SCALE))
#define SCORPION_FRAME_RATE 0.08f
#define SCORPION_FRAMES 4
#define SCORPION_SPAWN_RATE 20.0f
#define SCORPION_WAVE_MIN 3

#define PLAYER_LIVES 3
#define DEATH_DELAY 1.5f
#define WAVE_CLEAR_DELAY 1.0f
#define MUSHROOM_SPAWN_INTERVAL 0.05f

#define SCORE_MUSHROOM 1
#define SCORE_CENTIPEDE_BODY 10
#define SCORE_CENTIPEDE_HEAD 100
#define SCORE_SPIDER_CLOSE 900
#define SCORE_SPIDER_MID 600
#define SCORE_SPIDER_FAR 300
#define SCORE_FLEA 200
#define SCORE_SCORPION 1000

#define HEAL_FRAMES 6
#define HEAL_FRAME_RATE 0.08f

#define WAVE_SPEED_INC 10.0f